apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-ui
  labels:
    app: orchestrator-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orchestrator-ui
  template:
    metadata:
      labels:
        app: orchestrator-ui
    spec:
      containers:
        - name: orchestrator-ui
          image: jeromejoseph/orchestrator-ui:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: orchestrator-config
