apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-service
  labels:
    app: scanner-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scanner-service
  template:
    metadata:
      labels:
        app: scanner-service
    spec:
      containers:
        - name: scanner-service
          image: jeromejoseph/scanner-service:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
