---
- name: Checkout scanner repo
  git:
    repo: 'https://github.com/pentest-labz/scanner-service.git'
    dest: /opt/scanner

- name: Build Docker image
  community.docker.docker_image:
    build:
      path: /opt/scanner
    name: jeromejoseph/scanner
    tag: "main"

- name: Push image to registry
  community.docker.docker_image:
    name: jeromejoseph/scanner:main
    push: yes
