apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-service
  labels:
    app: orchestrator-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orchestrator-service
  template:
    metadata:
      labels:
        app: orchestrator-service
    spec:
      containers:
        - name: orchestrator-service
          image: jeromejoseph/orchestrator-service:latest
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: orchestrator-config
            - secretRef:
                name: orchestrator-secrets
