---
- hosts: masters
  gather_facts: no
  vars:
    kubeconfig_path: /etc/kubernetes/admin.conf
  tasks:
    - name: Deploy scanner Deployment & Service
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file','roles/scanner/templates/scanner-deployment.yml') }}"

    - name: Deploy auth
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file','roles/auth/templates/auth-deployment.yml') }}"
    
    - name: Deploy bruteforce
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file','roles/bruteforce/templates/brute-force-deployment.yml') }}"
    
    - name: Deploy sqlinjector
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file','roles/sqlinjector/templates/sql-injector-deployment.yml') }}"

    - name: Deploy orchestrator-frontend
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file','roles/sqlinjector/templates/orchestrator-frontend.yml') }}"    

    - name: Deploy orchestrator-backend
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file','roles/sqlinjector/templates/orchestrator-backend.yml') }}"

    - name: Deploy HorizontalPodAutoscaler for scanner
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file','roles/scanner/templates/scanner-hpa.yml') }}"
