---
- hosts: masters
  gather_facts: no
  vars:
    kubeconfig_path: /etc/kubernetes/admin.conf
  tasks:
    - name: Deploy scanner Deployment & Service
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file','roles/scanner-service/templates/scanner-service-deployment.yml') }}"

    - name: Deploy auth-service
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file','roles/auth-service/templates/auth-service-deployment.yml') }}"
    
    - name: Deploy bruteforce-service
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file','roles/bruteforce-service/templates/bruteforce-service-deployment.yml') }}"
    
    - name: Deploy sql-exploit-service
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file','roles/sql-exploit-service/templates/sql-exploit-service-deployment.yml') }}"

    - name: Deploy orchestrator-ui
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file','roles/orchestrator-frontend/templates/orchestrator-ui.yml') }}"    

    - name: Deploy orchestrator-service
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file','roles/orchestrator-backend/templates/orchestrator-service.yml') }}"

    - name: Deploy HorizontalPodAutoscaler for scanner-service
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file','roles/scanner-service/templates/scanner-service-hpa.yml') }}"

    - name: Deploy HorizontalPodAutoscaler for auth-service
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file','roles/auth-service/templates/auth-service-hpa.yml') }}"
    
    - name: Deploy HorizontalPodAutoscaler for bruteforce-service
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file','roles/scanner/templates/bruteforce-service-hpa.yml') }}"

    - name: Deploy HorizontalPodAutoscaler for orchestrator-ui
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file','roles/orchestrator-ui/templates/orchestrator-ui-hpa.yml') }}"

    - name: Deploy HorizontalPodAutoscaler for orchestrator-service
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file','roles/orchestrator-service/templates/orchestrator-service-hpa.yml') }}"

    - name: Deploy HorizontalPodAutoscaler for sql-exploit-service
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file','roles/sql-exploit-service/templates/sql-exploit-service-hpa.yml') }}"

